# condition: service_completed_successfully
# condition: service_started
# condition: service_healthy

version: '3.9'

services:
  db:
    image: mysql
    restart: on-failure
    volumes:
      - type: volume
        source: DATA_DB
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3355:3306

  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080

  mq:
    image: rabbitmq:3-management
    restart: on-failure
    healthcheck:
        test: "exit 0"
    environment:
      - RABBITMQ_DEFAULT_USER=tung
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 5672:5672
      - 15672:15672
  
  member:
    build:
      context: ../CommonPractices__V3
      dockerfile: MemberDockerfile
    environment:
      DB_CONNECTION_STRING: server=db;user id=root;password=123456;port=3306;database=Members;
      ASPNETCORE_ENVIRONMENT: Development
    restart: on-failure
    depends_on:
      - db
    ports:
      - 6001:80
  
  course:
    build:
      context: ../CommonPractices__V3
      dockerfile: CourseDockerfile
    environment:
      DB_CONNECTION_STRING: server=db;user id=root;password=123456;port=3306;database=Course;
      BASE_MEMBER_SERVICE_URI: http://member:80/api/Members/
      ASPNETCORE_ENVIRONMENT: Development
      RETRY_COUNT: 3
      TIME_OUT: 5
      MQ_HOST: rabbitmq://mq:5672
    restart: on-failure
    depends_on:
      db:
        condition: service_started
      member:
        condition: service_started
      mq:
        condition: service_healthy
    ports:
      - 6002:80

  notification:
    build:
      context: ../CommonPractices__V3
      dockerfile: NotificationDockerfile
    environment:
      MQ_HOST: rabbitmq://mq:5672

      # ------------- Back up -------------- #
      # MAILTRAP_USERNAME: bc67008ddc861d
      # MAILTRAP_PASSWORD: c9f6b92eccf837
      # MAILTRAP_HOST: smtp.mailtrap.io

      # Để trống Authen để sinh ra SmtpException
      MAILTRAP_USERNAME: bc67008ddc861d
      MAILTRAP_PASSWORD: c9f6b92eccf837

      # Để trống HOST để sinh ra InvalidOperationException
      MAILTRAP_HOST: smtp.mailtrap.io

    restart: on-failure
    stdin_open: true
    tty: true
    depends_on:
      mq:
        condition: service_healthy
    ports:
      - 2525:2525
  
  report:
    build:
      context: ../CommonPractices__V3
      dockerfile: ReportDockerfile
    environment:
      DB_CONNECTION_STRING: server=db;user id=root;password=123456;port=3306;database=Report;
      MQ_HOST: rabbitmq://mq:5672
      ASPNETCORE_ENVIRONMENT: Development
      DOCKER_ENVIRONMENT: docker
    restart: on-failure
    depends_on:
      mq:
        condition: service_healthy
    ports:
      - 6003:80

  # gateway:
  #   build:
  #     context: ../CommonPractices__V3
  #     dockerfile: APIGatewayDockerfile
  #   restart: on-failure
  #   depends_on:
  #     member:
  #       condition: service_started
  #     course:
  #       condition: service_started
  #   ports:
  #     - 6004:80

volumes:
  DATA_DB: