version: '3.9'

services:
  mq:
    image: rabbitmq:3-management
    restart: on-failure
    healthcheck:
        test: "exit 0"
    environment:
      - RABBITMQ_DEFAULT_USER=tung
      - RABBITMQ_DEFAULT_PASS=123456
    ports:
      - 5672:5672
      - 15672:15672
  